from __future__ import annotations

from collections.abc import Awaitable, Callable
from datetime import datetime
from typing import Any, Protocol

from headsup.models import CalendarEvent, Card, FreeSlot, GeoPoint, Place, Profile, RouteEta

CallbackHandler = Callable[[int, int, str], Awaitable[None]]
ReplyHandler = Callable[[int, str], Awaitable[None]]
CommandHandler = Callable[[int, list[str]], Awaitable[None]]


class Channel(Protocol):
    async def push(self, chat_id: int, card: Card) -> int: ...
    async def edit(self, chat_id: int, message_id: int, text: str) -> None: ...
    async def send_text(self, chat_id: int, text: str) -> int: ...
    def on_callback(self, fn: CallbackHandler) -> None: ...
    def on_reply(self, fn: ReplyHandler) -> None: ...
    def on_command(self, name: str, fn: CommandHandler) -> None: ...
    async def run(self) -> None: ...


class Calendar(Protocol):
    def list_events(self, start: datetime, end: datetime) -> list[CalendarEvent]: ...
    def free_slots(self, start: datetime, end: datetime, min_minutes: int) -> list[FreeSlot]: ...
    def insert_event(self, title: str, start: datetime, end: datetime, location: str | None = None) -> CalendarEvent: ...


class Maps(Protocol):
    async def route_eta(self, origin: str, destination: str, depart_at: datetime, traffic_aware: bool = True) -> RouteEta: ...
    async def find_places(self, query: str, near: GeoPoint, open_now: bool = True, limit: int = 3) -> list[Place]: ...
    async def geocode(self, text: str) -> GeoPoint: ...


class Reminders(Protocol):
    def schedule(self, at: datetime, chat_id: int, text: str) -> str: ...
    def cancel(self, reminder_id: str) -> None: ...


class Booking(Protocol):
    def checkout_url(self, url: str | None, title: str) -> str: ...


class ProfileStore(Protocol):
    def get(self) -> Profile: ...
    def update(self, patch: dict[str, Any]) -> Profile: ...
